workflows:
  xamarin_build:
    name: Xamarin Build Workflow
    environment:
      vars:
        ANDROID_KEYSTORE_PATH: "$HOME/.android/keystore.jks"
        ANDROID_KEYSTORE_PASSWORD: "$KEYSTORE_PASSWORD"
        ANDROID_KEY_ALIAS: "$KEY_ALIAS"
        ANDROID_KEY_PASSWORD: "$KEY_PASSWORD"
    scripts:
      - name: Install Dependencies
        script: |
          # Ensure the package manager is updated
          brew update
          
          # Install .NET SDK (make sure to use ARM version)
          brew install --cask dotnet-sdk

          # Install Xamarin dependencies
          brew install --cask visual-studio # Install Visual Studio for Mac (Xamarin)
          
          # Install Java and Android SDK
          brew install openjdk@11
          brew install android-sdk
          
          # Install NuGet if not available
          curl -sSL https://aka.ms/install-nuget-cli | bash

      - name: Restore Dependencies
        script: |
          # Restore Xamarin project dependencies using dotnet
          dotnet restore MyXamarinProject.sln # Adjust for your solution file

      - name: Build Xamarin Project
        script: |
          # Build Xamarin Project with MSBuild for macOS ARM
          msbuild MyXamarinProject.sln /p:Configuration=Release /p:Platform="Any CPU" # Ensure MSBuild targets ARM for macOS

      - name: Build Android APK (if applicable)
        script: |
          # Build the Android APK using MSBuild for Xamarin Android
          msbuild MyXamarinProject/MyXamarinProject.Android/MyXamarinProject.Android.csproj /p:Configuration=Release /p:Platform="x86_64" # Adjust for your Android project

